name: AWS Caller Identity

on:
  pull_request: 
  push:
    branches:
      - gh-actions-debug

jobs:
  run-aws-command:
    name: Run AWS Command
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.NEW_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.NEW_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      
      - name: Run AWS Command
        run: aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.NEW_AWS_ACCESS_KEY_ID }} # Use the secret you have set up
          AWS_SECRET_ACCESS_KEY: ${{ secrets.NEW_AWS_SECRET_ACCESS_KEY }} # Use the secret you have set up
          AWS_DEFAULT_REGION: us-east-1  